import{DEFAULT_CONFIG,TEMPLATES,buildSvg,sanitizeConfig}from"./svg-generator.js";
const state=sanitizeConfig(JSON.parse(localStorage.getItem("readme-motion-config")||"{}"));
const preview=document.querySelector("#preview"),templateGrid=document.querySelector("#templateGrid"),toast=document.querySelector("#toast");let previewUrl,timer;
function notify(message){toast.textContent=message;toast.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove("show"),2200);}
function persist(){localStorage.setItem("readme-motion-config",JSON.stringify(state));}
function render(){const svg=buildSvg(state);if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));preview.src=previewUrl;document.querySelectorAll("[data-field]").forEach(input=>{if(input.type!=="file"&&document.activeElement!==input)input.value=state[input.dataset.field]??"";});document.querySelectorAll("[data-color-output]").forEach(output=>output.value=state[output.dataset.colorOutput].toUpperCase());document.querySelectorAll(".template-card").forEach(card=>card.classList.toggle("active",card.dataset.template===state.template));persist();return svg;}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),200);}
async function copy(text,message){try{await navigator.clipboard.writeText(text);notify(message);}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();notify(message);}}
for(const template of TEMPLATES){const button=document.createElement("button");button.type="button";button.className="template-card";button.dataset.template=template.id;button.innerHTML=`<span class="template-swatch" style="background:radial-gradient(circle at 20% 20%,${template.primary}55,transparent 42%),linear-gradient(135deg,${template.background},#111827);--swatch-accent:${template.secondary}"></span><b>${template.name}</b><small>${template.note}</small>`;button.addEventListener("click",()=>{Object.assign(state,{template:template.id,primary:template.primary,secondary:template.secondary});render();});templateGrid.append(button);}
document.querySelectorAll("[data-field]").forEach(input=>{input.value=state[input.dataset.field]??input.value;input.addEventListener("input",()=>{state[input.dataset.field]=input.value;render();});});
document.querySelector("#avatarInput").addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;if(file.size>1_500_000){notify("Please choose an image under 1.5 MB");return;}const reader=new FileReader();reader.onload=()=>{state.avatar=reader.result;render();notify("Avatar embedded in your SVG");};reader.readAsDataURL(file);});
document.querySelector("#resetButton").addEventListener("click",()=>{Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,DEFAULT_CONFIG);document.querySelector("#avatarInput").value="";render();notify("Design reset");});
document.querySelector("#downloadSvg").addEventListener("click",()=>{download(buildSvg(state),"hero.svg","image/svg+xml");notify("SVG downloaded");});
document.querySelector("#copySvg").addEventListener("click",()=>copy(buildSvg(state),"SVG copied"));
document.querySelector("#copyMarkdown").addEventListener("click",()=>copy('<img width="100%" src="./assets/hero.svg" alt="Animated profile hero" />',"Markdown copied"));
document.querySelector("#exportConfig").addEventListener("click",()=>{download(JSON.stringify(state,null,2),"readme-motion.json","application/json");notify("Configuration exported");});
document.querySelector("#importConfig").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;try{Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,sanitizeConfig(JSON.parse(await file.text())));render();notify("Configuration imported");}catch{notify("That configuration is not valid");}event.target.value="";});
render();
